project:
  type: website
  output-dir: _site

website:
  title: "Islamic Wisdom & Nature"
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
      - text: "Chemistry"
        href: chemistry.html
      - text: "Quotes"
        href: quotes.qmd
      - text: "Gallery"
        href: gallery.qmd
      - text: "Inspiration"
        href: inspiration.html
      - text: "Support Us"
        href: support.html
    right:
      - icon: github
        href: https://github.com
      - icon: twitter
        href: https://twitter.com

format:
  html:
    theme: 
      light: [cosmo, custom.scss]
    css: styles.css
    toc: true
    page-layout: full
